name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: debian:12

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libopencv-dev git cmake build-essential

      - name: Clone tengine-lite-yolov5s-tt100k repo and build
        run: |
          git clone https://github.com/Truoji/tengine-lite-yolov5s-tt100k
          cd tengine-lite-yolov5s-tt100k
          sed -i 's/SHARED/STATIC/g' CMakeLists.txt
          sed -i 's/libtengine-lite.so/libtengine-lite-static.a/g' CMakeLists.txt
          sed -i '/find_package(OpenCV REQUIRED)/a find_package(OpenMP REQUIRED)' CMakeLists.txt
          sed -i 's/target_link_libraries(yolov5s-tt100k tengine ${OpenCV_LIBS})/target_link_libraries(yolov5s-tt100k tengine OpenMP::OpenMP_CXX ${OpenCV_LIBS})/' CMakeLists.txt
          mkdir -p build && cd build && rm -f CMakeCache.txt && cmake .. && make

      - name: Upload build artifacts to GitHub Release
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: tengine-lite-yolov5s-tt100k/build/yolov5s-tt100k

      - name: Get latest release
        id: latest_release
        uses: actions/github-script@v4
        with:
          script: |
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const latestRelease = releases.data[0];
            return latestRelease.upload_url.split("{?")[0];

      - name: Upload build artifacts to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release.outputs.result }}
          asset_path: ./tengine-lite-yolov5s-tt100k/build/yolov5s-tt100k
          asset_name: yolov5s-tt100k
          asset_content_type: application/octet-stream
